# TODO: Initialization statement (arrays and in general).
# TODO: Const pointers and array types.
# TODO: imports and exports.
# TODO: range syntax.
# TODO: utf-8 character literals etc.
# TODO: All operations and in nonReturnStatement. 
# TODO: array and struct implementations.
# TODO: vectors and matrices.

# ------------------------
# --- Compilation Unit ---
# ------------------------
compilationUnit ::= { declaration }

# ------------------
# --- Expression ---
# ------------------ 
functionExpression ::= functionTypeExpression blockExpression

nonReturnStatement ::= unimplemented SEMI

returnStatement ::= RETURN expression SEMI

blockExpression ::= LEFT_BRACE {nonReturnStatement} [ returnStatement | expression ] RIGHT_BRACE

parExpression ::= LEFT_PAREN expression RIGHT_PAREN

ifExpression ::= IF parExpression blockExpression { ELSE IF parExpression blockExpression } [ ELSE blockExpression ]

valueExpression ::= INT_LITERAL | FLOAT_LITERAL | STRING_LITERAL | CHAR_LITERAL

arrayInitExpression ::= unimplemented

structInitExpression ::= unimplemented

expression ::= blockExpression
             | functionExpression
             | valueExpression # base case of expression.
             | ifExpression
             | parExpression
             | arrayInitExpression
             | structInitExpression

# -------------
# --- TYPES ---
# -------------
intrinsicTypeExpression ::= VOID
                          | BOOL
                          | F32 | F64
                          | U8 | I8 | U16 | I16 | U32 | I32 | U64 | I64
                          | CHAR8 | CHAR16 | CHAR32

emptyStructExpression ::= STRUCT LEFT_BRACE RIGHT_BRACE
structMember          ::= [ PUB ] identifier COLON typeExpression
structExpression      ::= emptyStructExpression 
                        | ( STRUCT LEFT_BRACE 
                                structMember { COMMA structMember } [ COMMA ] 
                            RIGHT_BRACE )

# TODO: enumExpression and flagExpression
anonymousTypeExpression ::= structExpression
                          | enumExpression
                          | flagExpression

functionParameter      ::= [ IDENTIFIER COLON ] typeExpression 
functionParameters     ::= functionParameter { COMMA functionParameter }
functionTypeExpression ::= FN LEFT_PAREN [ functionParameters ] RIGHT_PAREN RETURN_ARROW typeExpression

pointerTypeExpression ::= STAR ( 
                            ( LEFT_PAREN functionTypeExpression RIGHT_PAREN ) | 
                            nonFunctionTypeExpression
                        )

arrayTypeExpression ::= LEFT_BRACKET RIGHT_BRACKET ( 
                            ( LEFT_PAREN functionTypeExpression RIGHT_PAREN ) | 
                            nonFunctionTypeExpression
                        )

nonFunctionTypeExpression ::= IDENTIFIER
                            | intrinsicTypeExpression 
                            | pointerTypeExpression
                            | arrayTypeExpression

nonAnonymousTypeExpression ::= nonFunctionTypeExpression | functionTypeExpression

typeExpression ::= nonAnonymousTypeExpression 
                 | anonymousTypeExpression


# -------------
# --- DECL ---
# -------------
mutability ::= const | var | comptime

varDecl ::=
    [ PUB ] mutability identifier [ COLON typename ] EQ ( expression | UNDEFINED ) SEMI

typeDecl ::=
    [ PUB ] TYPE identifier EQ typeExpression

declaration ::= varDecl
              | typeDecl


# -------------
# --- MISC ---
# -------------
unimplemented ::= ""
