# TODO: Initialization statement (arrays and in general).
# TODO: Const pointers and array types.
# TODO: imports and exports.
# TODO: range syntax.
# TODO: utf-8 character literals etc.
# TODO: All operations and in nonReturnStatement. 
# TODO: array and struct implementations.
# TODO: vectors and matrices.
# TODO: slice array syntax

# ------------------------
# --- Compilation Unit ---
# ------------------------
compilationUnit ::= { declaration }

# -----------------
# --- Statement ---
# -----------------
assignmentStatement ::= unaryExpression PLUS_EQ expression       
                      | unaryExpression MINUS_EQ expression      
                      | unaryExpression STAR_EQ expression
                      | unaryExpression STAR_STAR_EQ expression
                      | unaryExpression SLASH_EQ expression
                      | unaryExpression PERCENT_EQ expression
                      | unaryExpression CARE_EQ expression   
                      | unaryExpression TILDE_EQ expression
                      | unaryExpression PIPE_EQ expression
                      | unaryExpression AMPERSAND_EQ expression
                      | unaryExpression LEFT_SHIFT_EQ  expression
                      | unaryExpression RIGHT_SHIFT_EQ expression

controlFlowStopStatement ::= ( BREAK | CONTINUE ) SEMI

doLoop ::= DO blockExpression WHILE parExpression SEMI

emptyStatement ::= SEMI

expressionStatement ::= expression SEMI

forLoop ::= unimplemented

loopLoop ::= LOOP blockExpression

whileLoop ::= WHILE parExpression blockExpression

nonReturnStatement ::= varDecl 
                     | typeDecl  
                     | controlFlowStopStatement
                     | doLoop
                     | emptyStatement
                     | expressionStatement 
                     | forLoop
                     | loopLoop
                     | whileLoop

returnStatement ::= RETURN expression SEMI

# ------------------
# --- Expression ---
# ------------------
functionCaptureGroup ::= LEFT_BRACKET { [ REF | EQ ] IDENTIFIER COMMA } [ REF | EQ ] IDENTIFIER RIGHT_BRACKET

functionValueExpression ::= FN LEFT_PAREN [ functionParameters ] RIGHT_PAREN 
    [ functionCaptureGroup ] RETURN_ARROW typeExpression blockExpression

blockExpression ::= LEFT_BRACE { nonReturnStatement } [ returnStatement | expression ] RIGHT_BRACE

parExpression ::= LEFT_PAREN expression RIGHT_PAREN

ifExpression ::= IF parExpression blockExpression { ELSE IF parExpression blockExpression } [ ELSE blockExpression ]

valueExpression ::= INT_LITERAL | FLOAT_LITERAL | STRING_LITERAL | CHAR_LITERAL | TRUE | FALSE | NULL | IDENTIFIER

arrayInitExpression ::= LEFT_BRACKET [ expression { COMMA expression } ] RIGHT_BRACKET

structInitExpression ::= unimplemented

baseExpression (Zero) ::= blockExpression
                 | functionValueExpression
                 | valueExpression # base case of expression.
                 | ifExpression
                 | parExpression
                 | arrayInitExpression
                 | structInitExpression

arrayAccessExpression ::= postFixExpression LEFT_BRACKET expression RIGHT_BRACKET

functionCallExpression ::= postFixExpression LEFT_PAREN [ expression { COMMA expression } ]  RIGHT_PAREN

fieldAccessExpression ::= postFixExpression DOT identifier

scopeResolutionExpression ::= postFixExpression COLON_COLON identifier

postFixExpresion (One) ::= baseExpression
                         | arrayAccessExpression
                         | functionCallExpression
                         | fieldAccessExpression
                         | scopeResolutionExpression

addressExpression ::= AMPERSAND unaryExpression

alignExpression ::= ALIGN unaryExpression

complementExpression ::= TILDE unaryExpression

dereferenceExpression ::= STAR unaryExpression

negationExpression ::= MINUS unaryExpression

notExpression ::= BANG unaryExpression

referenceExpression ::= REF unaryExpression

unaryExpression (Two) ::= postFixExpression
                        | addressExpression
                        | alignExpression
                        | complementExpression
                        | dereferenceExpression
                        | negationExpression
                        | notExpression
                        | referenceExpression
                        | sizeOfExpression

exponentExpression (Three) ::= unaryExpression
                             | exponentExpression STAR_STAR unaryExpression

multiplicativeExpression (Four) ::= exponentExpression
                                  | multiplicativeExpression STAR exponentExpression
                                  | multiplicativeExpression SLASH exponentExpression
                                  | multiplicativeExpression PERCENT exponentExpression

additiveExpression (Five) ::= multiplicativeExpression
                            | additiveExpression PLUS multiplicativeExpression 
                            | additiveExpression MINUS multiplicativeExpression

shiftExpression (Six) ::= additiveExpression
                        | shiftExpression LEFT_SHIFT additiveExpression
                        | shiftExpression RIGHT_SHIFT additiveExpression

relationalExpression (Seven) ::= shiftExpression
                               | relationalExpression LESS shiftExpression
                               | relationalExpression LESS_EQ shiftExpression
                               | relationalExpression GREATER shiftExpression
                               | relationalExpression GREATER_EQ shiftExpression

equalityExpression (Eight) ::= relationalExpression
                             | equalityExpression EQ_EQ relationalExpression
                             | equalityExpression BANG_EQ relationalExpression

bitwiseAndExpression (Nine) ::= equalityExpression
                              | bitwiseAndExpression AMPERSAND equalityExpression

bitwiseXORExpression (Ten) ::= bitwiseAndExpression
                             | bitwiseXORExpression CARET bitwiseAndExpression

bitwiseOrExpression (Eleven) ::= bitwiseXORExpression
                               | bitwiseOrxpression PIPE bitwiseXORExpression

logicalAndExpression (Twelve) ::= bitwiseOrExpression
                                | logicalAndExpression AND bitwiseOrExpression

logicalOrExpression (Twelve) ::= logicalAndExpression
                               | logicalOrExpression OR logicalAndExpression

expression ::= logicalOrExpression

# -------------
# --- TYPES ---
# -------------
intrinsicTypeExpression ::= VOID
                          | BOOL
                          | F32 | F64
                          | U8 | I8 | U16 | I16 | U32 | I32 | U64 | I64
                          | CHAR8 | CHAR16 | CHAR32

emptyStructExpression ::= STRUCT LEFT_BRACE RIGHT_BRACE
structMember          ::= [ PUB ] identifier COLON typeExpression
structExpression      ::= emptyStructExpression 
                        | ( STRUCT LEFT_BRACE 
                                structMember { COMMA structMember } [ COMMA ] 
                            RIGHT_BRACE )

# TODO: enumExpression and flagExpression
anonymousTypeExpression ::= structExpression
                          | enumExpression
                          | flagExpression

functionParameter      ::= [ IDENTIFIER COLON ] typeExpression 
functionParameters     ::= functionParameter { COMMA functionParameter }
functionTypeExpression ::= FN LEFT_PAREN [ functionParameters ] RIGHT_PAREN RETURN_ARROW typeExpression

pointerTypeExpression ::= STAR ( 
                            ( LEFT_PAREN functionTypeExpression RIGHT_PAREN ) | 
                            nonFunctionTypeExpression
                        )

arrayTypeExpression ::= LEFT_BRACKET [ expression ] RIGHT_BRACKET ( 
                            ( LEFT_PAREN functionTypeExpression RIGHT_PAREN ) | 
                            nonFunctionTypeExpression
                        )

referenceTypeExpression ::= REF nonFunctionTypeExpresson

nonFunctionTypeExpression ::= IDENTIFIER
                            | intrinsicTypeExpression 
                            | pointerTypeExpression
                            | arrayTypeExpression
                            | referenceTypeExpression

nonAnonymousTypeExpression ::= nonFunctionTypeExpression | functionTypeExpression

typeExpression ::= nonAnonymousTypeExpression 
                 | anonymousTypeExpression


# -------------
# --- DECL ---
# -------------
mutability ::= CONST | VAR | COMPTIME

varDecl ::=
    [ PUB ] mutability identifier [ COLON typename ] EQ ( expression | UNDEFINED ) SEMI

typeDecl ::=
    [ PUB ] TYPE identifier EQ typeExpression SEMI

declaration ::= varDecl
              | typeDecl


# -------------
# --- MISC ---
# -------------
unimplemented ::= ""
