# --------------------------------
# Reserved Words
# --------------------------------
AND          ::= "and"
BREAK        ::= "break"
COMPTIME     ::= "comptime"
CONST        ::= "const"
CONTINUE     ::= “continue”
DO           ::= "do"
ELSE         ::= “else”
ENUM         ::= "enum"
FALSE        ::= "false"
FLAG         ::= "flag"
FN           ::= "fn"
FOR          ::= "for"
IF           ::= “if”
IN           ::= "in"
LOOP         ::= “loop”
NULL         ::= "null"
OR           ::= "or"
PUB          ::= "pub"
REF          ::= "ref"
RETURN       ::= "return"
STRUCT       ::= "struct"
SWITCH       ::= "switch"
TRUE         ::= "true"
TYPE         ::= "type"
UNDEFINED    ::= "undefined"
UNION        ::= "union"
VAR          ::= "var"
VEC          ::= "vec" # VEC and VOLATILE possibly to be removed.
VOLATILE     ::= "volatile"
WHILE        ::= “while”

F32 ::= “f32”
F64 ::= “f64”
F80 ::= maybe

U8 ::= “u8”
I8 ::= “i8”
U16 ::= “u16”
I16 ::= “i16”
U16 ::= “u16”
I32 ::= “i32”
U64 ::= “u64”
I64 ::= “i64”

BOOL   ::= "bool"
CHAR8  ::= "char8"
CHAR16 ::= "char16"
CHAR32 ::= "char32"
VOID   ::= "void"

# --------------------------------
# Punctuation
# --------------------------------
ALIGN        ::= "@alignof"
AS           ::= "@as"
SIZEOF       ::= "@sizeof"

# --------------------------------
# Punctuation
# --------------------------------
PLUS_EQ        ::= "+="
MINUS_EQ       ::= "-="
STAR_EQ        ::= "*="
STAR_STAR_EQ   ::= "**="
SLASH_EQ       ::= "/="
PERCENT_EQ     ::= "%="
CARE_EQ        ::= "^="
TILDE_EQ       ::= "~="
PIPE_EQ        ::= "|="
AMPERSAND_EQ   ::= "&="
LEFT_SHIFT_EQ  ::= "<<="
RIGHT_SHIFT_EQ ::= ">>="

LESS_EQ        ::= "<="
GREATER_EQ     ::= ">="
EQ_EQ          ::= "=="
BANG_EQ        ::= "!="
PLUS         ::= "+"
MINUS        ::= "-"
STAR         ::= "*"
STAR_STAR    ::= "**"
SLASH        ::= "/"
PERCENT      ::= "%"
DOT          ::= "."
COLON        ::= ":"
COLON_COLON  ::= "::"
SEMI         ::= ";"

LESS       ::= "<"
GREATER    ::= ">"
EQ         ::= "="
BANG       ::= "!"

CARET        ::= "^"
TILDE        ::= "~"
PIPE         ::= "|"
AMPERSAND    ::= "&"

LEFT_SHIFT     ::= "<<"
RIGHT_SHIFT    ::= ">>"

RANGE_LESS ::= "..<"
RANGE_EQ       ::= "..="

DEREF        ::= ".*"
RETURN_ARROW ::= "->"
SWITCH_ARROW ::= "=>"

COMMA         ::= ","
SINGLE_QUOTE  ::= "'"
DOUBLE_QUOTE  ::= '"'
LEFT_BRACKET  ::= "["
RIGHT_BRACKET ::= "]"
LEFT_PAREN    ::= "("
RIGHT_PAREN   ::= ")"
LEFT_BRACE    ::= "{"
RIGHT_BRACE   ::= "}"

# --------------------------------
# Literals
# --------------------------------
HEX_DIGIT     ::= ( "0" ... "9" ) | ( "a" ... "f" ) | ( "A" ... "F" )
HEX_DIGITS    ::= HEX_DIGIT { HEX_DIGIT }
DIGIT         ::= ( "0" ... "9" )
DIGITS        ::= DIGIT { DIGIT }
EXPONENT      ::= ( "e" | "E" ) [ ( "+" | "-" ) ] DIGITS
INT_LITERAL   ::=  DIGITS { [ "'" ] DIGITS }
                | "0x" HEX_DIGITS { [ "'" ] HEX_DIGITS }
FLOAT_LITERAL ::= [ INT_LITERAL ] "." INT_LITERAL [ EXPONENT ]
                | INT_LITERAL "." [ INT_LITERAL ] [ EXPONENT ]

ESC_SEQUENCE   ::= "\\" ( "n" | "r" | "t" | "b" | "f" | "’" | "\"" | "\\" )
STRING_LITERAL ::= "\"" { ESC_SEQUENCE | ~( "\"" | "\\" | "\n" | "\r" ) } "\""
CHAR_LITERAL   ::= "’" ( ESC_SEQUENCE | ~( "’" | "\n" | "\r" | "\\" ) ) "’"

NON_DIGIT           ::= _ | ( "a" ... "z" ) | ( "A" ... "Z" )
IDENTIFIER_START    ::= NON_DIGIT | XID_START
IDENTIFIER_CONTINUE ::= DIGIT | NON_DIGIT | XID_CONTINUE
IDENTIFER           ::= IDENTIFIER_START { IDENTIFIER_CONTINUE }

EOF ::= <EOF>